web:
  build: .
  dockerfile: Dockerfile
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - /etc/letsencrypt:/etc/letsencrypt
   - /etc/ssl/certs:/dh
  environment:
   - SQLALCHEMY_DATABASE_URI=postgresql://root:root@db/fellowtraveler
  links:
   - db

db:
  image: postgres:9.6-alpine
  volumes:
    - /home/aksakal/pgdata:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=root
   - POSTGRES_USER=root
   - POSTGRES_DB=fellowtraveler
